name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
      
      - name: setup ms-build
        run: sudo apt-get install -y nuget mono-devel mono-xbuild

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build DotNetWebsite -p:Configuration=Release